### ISSUE TITLE
初始化个推SDK报错

### ISSUE THREAD

**Issue by AndroidZern** [GetuiLaboratory/getui-flutter-plugin#3]
flutter: got zone error: MissingPluginException(No implementation found for method initGetuiPush on channel getuiflut), #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:300:7)
<asynchronous suspension>
#1      Getuiflut.initGetuiSdk (package:getuiflut/getuiflut.dart:38:20)
<asynchronous suspension>
#2      GeTuiUtils.initGetuiSdk (package:b2b/utils/getui.dart:23:17)
<asynchronous suspension>

// 文档和demo能否说明的详细一点。

**Comment by Holy-Fak** [comment]
兄弟怎么解决的
