### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by simanlx** [GetuiLaboratory/getui-flutter-plugin#53]
E/AndroidRuntime(24175): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/igexin/sdk/PushManager;
E/AndroidRuntime(24175): 	at com.getui.getuiflut.GetuiflutPlugin.bindAlias(GetuiflutPlugin.java:210)
E/AndroidRuntime(24175): 	at com.getui.getuiflut.GetuiflutPlugin.onMethodCall(GetuiflutPlugin.java:135)
E/AndroidRuntime(24175): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/AndroidRuntime(24175): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/AndroidRuntime(24175): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/AndroidRuntime(24175): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/AndroidRuntime(24175): 	at android.os.Handler.handleCallback(Handler.java:942)
E/AndroidRuntime(24175): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(24175): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(24175): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(24175): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/AndroidRuntime(24175): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(24175): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(24175): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/AndroidRuntime(24175): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.igexin.sdk.PushManager" on path: DexPathList[[zip file "/data/app/~~84uKaMG_fkX8rGJULq-TtA==/com.example.openim_enterprise_chat-qU12zlEs5-tonFA9Fd8elA==/base.apk"],nativeLibraryDirectories=[/data/app/~~84uKaMG_fkX8rGJULq-TtA==/com.example.openim_enterprise_chat-qU12zlEs5-tonFA9Fd8elA==/lib/x86_64, /data/app/~~84uKaMG_fkX8rGJULq-TtA==/com.example.openim_enterprise_chat-qU12zlEs5-tonFA9Fd8elA==/base.apk!/lib/x86_64, /system/lib64, /system_ext/lib64]]
E/AndroidRuntime(24175): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
E/AndroidRuntime(24175): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(24175): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(24175): 	... 14 more
I/Process (24175): Sending signal. PID: 24175 SIG: 9
Lost connection to device.

**Comment by ohhhh1208** [comment]
同样的问题，请问解决了吗
